# ------------------------------- NAMESPACE ----------------------------------
apiVersion: v1 # API group for core objects like Namespace
kind: Namespace # We create an isolated namespace for Glance
metadata:
  name: glance # The namespace name (you can change it)
---
# ------------------------------- CONFIGMAP ----------------------------------
apiVersion: v1 # Core API group again
kind: ConfigMap # Key/value or file-like data for pods
metadata:
  name: glance-config # ConfigMap name
  namespace: glance # Put it in the 'glance' namespace
data:
  # The key becomes the filename inside the container because we'll mount the
  # ConfigMap as files. Glance expects /app/config/glance.yml based on docs.
  # We'll name the key exactly 'glance.yml'.
  glance.yml: | # Start of the file content (literal block)
    # >>> BEGIN your Glance app configuration (copied from glance-config.yml) <<<
    pages:
      - name: Home
        # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
        # hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: twitch-channels
                channels:
                  - theprimeagen
                  - j_blow
                  - giantwaffle
                  - cohhcarnage
                  - christitustech
                  - EJ_SA

          - size: full
            widgets:
              - type: group
                widgets:
                  - type: hacker-news
                  - type: lobsters

              - type: videos
                channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
                  - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

              - type: group
                widgets:
                  - type: reddit
                    subreddit: technology
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true

          - size: small
            widgets:
              - type: weather
                location: Kassel, Germany
                units: metric
                hour-format: 12h # alternatively "24h"

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Jellyfin
                    url: https://yourdomain.com/
                    icon: si:jellyfin
                  - title: Gitea
                    url: https://yourdomain.com/
                    icon: si:gitea
                  - title: qBittorrent # only for Linux ISOs, of course
                    url: https://yourdomain.com/
                    icon: si:qbittorrent
                  - title: Immich
                    url: https://yourdomain.com/
                    icon: si:immich
                  - title: AdGuard Home
                    url: https://yourdomain.com/
                    icon: si:adguard
                  - title: Vaultwarden
                    url: https://yourdomain.com/
                    icon: si:vaultwarden

              - type: releases
                cache: 1d
                # Without authentication the Github API allows for up to 60 requests per hour. You can create a
                # read-only token from your Github account settings and use it here to increase the limit.
                # token: ...
                repositories:
                  - glanceapp/glance
                  - go-gitea/gitea
                  - immich-app/immich
                  - syncthing/syncthing
    # >>> END your Glance app configuration <<<
---
# ------------------------------- DEPLOYMENT ---------------------------------
apiVersion: apps/v1 # API group for Deployments
kind: Deployment # Ensures the desired number of pods is running
metadata:
  name: glance # Deployment name
  namespace: glance # Same namespace as above
spec:
  replicas: 1 # Run a single pod (increase for HA if needed)
  selector:
    matchLabels:
      app: glance # Label the Deployment will look for
  template: # Pod template (what to run)
    metadata:
      labels:
        app: glance # Labels placed on the pod (must match selector)
    spec:
      containers:
        - name: glance # Container name inside the pod
          # Official container image from the Glance project
          image: glanceapp/glance:latest # You can pin a version tag later
          imagePullPolicy: IfNotPresent # Avoid pulling if already cached
          ports:
            - containerPort:
                8080 # Glance listens on 8080 in the container
                # (as defined in the image)
                # Do not change containerPort, map at Service/Ingress instead.
          volumeMounts:
            - name: config # Mount our config volume
              mountPath:
                /app/config # Glance looks for /app/config/glance.yml
                # (matches Docker instructions)
              readOnly: true # ConfigMap is read-only inside pods
          # Optional: set resource requests/limits once you're comfy with K8s
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "64Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "256Mi"
      volumes:
        - name: config # Define a volume named 'config'
          configMap:
            name: glance-config # Source the ConfigMap we created
            items:
              - key: glance.yml # Only mount this single key
                path: glance.yml # As this filename in /app/config
---
# -------------------------------- SERVICE -----------------------------------
apiVersion: v1 # Core API for Services
kind: Service # Stable internal access to the pod(s)
metadata:
  name: glance # Service name
  namespace: glance # Same namespace
spec:
  type: ClusterIP # Internal-only service (default); expose via Ingress
  selector:
    app: glance # Route traffic to pods with this label
  ports:
    - name: http # Port name (used by Ingress too)
      port: 8080 # Service port inside the cluster
      targetPort:
        8080 # Forward to the containerPort on the pod
        # (Glance serves on 8080 by default)
---
# -------------------------------- INGRESS -----------------------------------
# Only apply this if you already run an ingress controller (e.g., NGINX or Traefik).
# It will let you access Glance at http(s)://glance.feanor.local/
apiVersion: networking.k8s.io/v1 # API group for Ingress
kind: Ingress # HTTP(S) routing to Services
metadata:
  name: glance
  namespace: glance
  annotations:
    # Example annotations for the NGINX ingress controller. If you use Traefik,
    # change accordingly or remove these annotations.
    kubernetes.io/ingress.class: traefik # Route with the nginx controller
spec:
  # If you use cert-manager, you can add a TLS section for automatic certs.
  # tls:
  #   - hosts:
  #       - glance.feanor.local
  #     secretName: glance-tls
  rules:
    - host: feanor # <-- CHANGE to your domain or remove host for nip.io testing
      http:
        paths:
          - path: / # Route all paths
            pathType: Prefix # Prefix match on the path
            backend:
              service:
                name: glance # Send to our Service named 'glance'
                port:
                  number: 8080 # Service port we defined above


