# ------------------------------- NAMESPACE ----------------------------------
apiVersion: v1 # API group for core objects like Namespace
kind: Namespace # We create an isolated namespace for Glance
metadata:
  name: glance # The namespace name (you can change it)
---
# ------------------------------- CONFIGMAP ----------------------------------
apiVersion: v1 # Core API group again
kind: ConfigMap # Key/value or file-like data for pods
metadata:
  name: glance-config # ConfigMap name
  namespace: glance # Put it in the 'glance' namespace
data:
  # The key becomes the filename inside the container because we'll mount the
  # ConfigMap as files. Glance expects /app/config/glance.yml based on docs.
  # We'll name the key exactly 'glance.yml'.
  glance.yml: | # Start of the file content (literal block)
    # >>> BEGIN your Glance app configuration (copied from glance-config.yml) <<<
    pages:
      - name: Home
        # Optionally, if you only have a single page you can hide the desktop navigation for a cleaner look
        # hide-desktop-navigation: true
        columns:
          - size: small
            widgets:
              - type: calendar
                first-day-of-week: monday

              - type: weather
                location: Kassel, Germany
                units: metric
                hour-format: 12h # alternatively "24h"

              - type: custom-api
                title: Epic Games
                cache: 1h
                url: https://store-site-backend-static.ak.epicgames.com/freeGamesPromotions?locale=de&country=DE&allowCountries=DE
                template: |
                  <div>
                    {{ if eq .Response.StatusCode 200 }}
                      <div class="horizontal-cards-2">
                        {{ range .JSON.Array "data.Catalog.searchStore.elements" }}
                          {{ $price := .String "price.totalPrice.discountPrice" }}
                          {{ $hasPromo := gt (len (.Array "promotions.promotionalOffers")) 0 }}
                          {{ if and $hasPromo (eq $price "0") }}
                            {{ $gamePage := .String "productSlug" }}
                            {{ if gt (len (.Array "offerMappings")) 0 }}
                              {{ $gamePage = .String "offerMappings.0.pageSlug" }}
                            {{end }}
                            <a href="https://store.epicgames.com/en-US/p/{{ $gamePage }}" target="_blank" class="card">
                              {{ $title := .String "title" }}
                              {{ range .Array "keyImages" }}
                                {{ if eq (.String "type") "OfferImageWide" }}
                                  <img src="{{ .String "url" }}" alt="{{ $title }}" style="width: 100%; max-width: 300px; height: 150px; object-fit: cover; border-radius: var(--border-radius);">
                                {{ end }}
                              {{ end }}
                              <div class="card-content">
                                <span class="size-base color-primary">{{ $title }}</span><br>
                                <span class="size-h5 color-subdue">
                                  {{ if $hasPromo }}
                                    {{ $promotions := .Array "promotions.promotionalOffers" }}
                                    {{ if gt (len $promotions) 0 }}
                                      {{ $firstPromo := index $promotions 0 }}
                                      {{ $offers := $firstPromo.Array "promotionalOffers" }}
                                      {{ if gt (len $offers) 0 }}
                                        {{ $firstOffer := index $offers 0 }}
                                        Free until {{ slice ($firstOffer.String "endDate") 0 10 }}
                                      {{ else }}
                                        Free this week!
                                      {{ end }}
                                    {{ else }}
                                      Free this week!
                                    {{ end }}
                                  {{ end }}
                                </span>
                              </div>
                            </a>
                          {{ end }}
                        {{ end }}
                      </div>
                    {{ else }}
                      <p class="color-negative">Error fetching Epic Games data.</p>
                    {{ end }}
                  </div>

          - size: full
            widgets:
              - type: videos
                channels:
                  - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
                  - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
                  - UCsBjURrPoezykLs9EqgamOA # Fireship
                  - UCBJycsmduvYEL83R_U4JriQ # Marques Brownlee
                  - UCHnyfMqiRRG1u-2MsSQLbXA # Veritasium

              - type: group
                widgets:
                  - type: reddit
                    subreddit: technology
                    show-thumbnails: true
                  - type: reddit
                    subreddit: selfhosted
                    show-thumbnails: true
                  - type: reddit
                    subreddit: homelab
                    show-thumbnails: true

          - size: small
            widgets:
              - type: server-stats
                servers:
                  - type: local
                    name: Services

              - type: monitor
                cache: 1m
                title: Services
                sites:
                  - title: Authentik
                    url: https://authentik.eldamar.dev/
                    icon: si:authentik
                  - title: Forgejo
                    url: https://forgejo.eldamar.dev/
                    icon: si:forgejo
                  - title: Jellyfin
                    url: https://jellyfin.eldamar.dev/
                    icon: si:jellyfin
                  - title: HomeAssistant
                    url: https://home-assistant.eldamar.dev/
                    icon: si:homeassistant

              - type: releases
                cache: 1d
                # Without authentication the Github API allows for up to 60 requests per hour. You can create a
                # read-only token from your Github account settings and use it here to increase the limit.
                # token: ...
                repositories:
                  - glanceapp/glance
                  - go-gitea/gitea
                  - immich-app/immich
                  - syncthing/syncthing
    # >>> END your Glance app configuration <<<
---
# ------------------------------- DEPLOYMENT ---------------------------------
apiVersion: apps/v1 # API group for Deployments
kind: Deployment # Ensures the desired number of pods is running
metadata:
  name: glance # Deployment name
  namespace: glance # Same namespace as above
spec:
  replicas: 1 # Run a single pod (increase for HA if needed)
  selector:
    matchLabels:
      app: glance # Label the Deployment will look for
  template: # Pod template (what to run)
    metadata:
      labels:
        app: glance # Labels placed on the pod (must match selector)
    spec:
      containers:
        - name: glance # Container name inside the pod
          # Official container image from the Glance project
          image: glanceapp/glance:latest # You can pin a version tag later
          imagePullPolicy: IfNotPresent # Avoid pulling if already cached
          ports:
            - containerPort:
                8080 # Glance listens on 8080 in the container
                # (as defined in the image)
                # Do not change containerPort, map at Service/Ingress instead.
          volumeMounts:
            - name: config # Mount our config volume
              mountPath:
                /app/config # Glance looks for /app/config/glance.yml
                # (matches Docker instructions)
              readOnly: true # ConfigMap is read-only inside pods
          # Optional: set resource requests/limits once you're comfy with K8s
          # resources:
          #   requests:
          #     cpu: "50m"
          #     memory: "64Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "256Mi"
      volumes:
        - name: config # Define a volume named 'config'
          configMap:
            name: glance-config # Source the ConfigMap we created
            items:
              - key: glance.yml # Only mount this single key
                path: glance.yml # As this filename in /app/config
---
# -------------------------------- SERVICE -----------------------------------
apiVersion: v1 # Core API for Services
kind: Service # Stable internal access to the pod(s)
metadata:
  name: glance # Service name
  namespace: glance # Same namespace
spec:
  type: ClusterIP # Internal-only service (default); expose via Ingress
  selector:
    app: glance # Route traffic to pods with this label
  ports:
    - name: http # Port name (used by Ingress too)
      port: 8080 # Service port inside the cluster
      targetPort:
        8080 # Forward to the containerPort on the pod
        # (Glance serves on 8080 by default)
---
# -------------------------------- INGRESS -----------------------------------
# Only apply this if you already run an ingress controller (e.g., NGINX or Traefik).
# It will let you access Glance at http(s)://glance.feanor.local/
apiVersion: networking.k8s.io/v1 # API group for Ingress
kind: Ingress # HTTP(S) routing to Services
metadata:
  name: glance
  namespace: glance
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  # If you use cert-manager, you can add a TLS section for automatic certs.
  ingressClassName: traefik
  tls:
    - hosts:
        - glance.eldamar.dev
      secretName: glance-tls
  rules:
    - host: glance.eldamar.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: glance
                port:
                  number: 8080



