---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ha-git-credentials
  namespace: home-assistant
spec:
  encryptedData:
    token: AgDH+Ch4mhl6r6GFWSDccr1uMfo6nShCr3Y0fDq1U2kvKqwqBS/UDs/tYwJdnSpRjRNU0FDmx8woy9TIWAzAwUiZnzaKDdCYd7VLz6enbKmqADkczhxjX/mBQGOHas1i5EEoiF4fU0XpTOemDQG2G6g0AGlPfCUqhpVQIPYbTHJUvuOkbDoDZOD9hG1dzkYl5gbAh0NqfEMKGQ1araGp6aiBh/kDYM+e35afdb3tYG8lxCnOEOsjzhtMlHVsO1buhIAruR8M5U9Bz1ATElfc+9CVILxQ2jrFdtccU3Lb2ZBs1W1I+qUtliI9kSw8HzedDNs4fxx7BaM8wTfD4/10KFmwu5gkOBzIcQDvxWpJ2SBRP6l2n/6bBqvc68WNMo7BvXw1w7596QNU04T6kCXFrTTV7MWP1n7ep6S4ParXyqnmSr0jzK3zgrwibeXhMN7A/WFWawV5j/Lguc4qmam5cOFN+jQRcqYM5Yu7FaDSp/yifafGLzn+ivg0T7VjA4JYBAThpM6GiVLe0Xo8R/4+Xfwjq86FVFiZAO0tEj8c1aRkSH8peQLi7A5cqc5IL3OQDHuLgYu46LpAPTwcV/OK8sJt6IJG/8/uEE2RcSfUM0rbarFUwywFUaViDUg+IfYJM0kgXsQ4k9exA7zWz64DDjvsNJb8il/8TO7SDtD00eP6pqp5rcJVeLHh8m6kg0AbyERQrPopc65M0ER7Hu4qL+h2lDpDNLLr2PfqZexMJZNpThVvcSGivScT
    username: AgCFXD53RYp2OxEHKYzlyIyr7adIRxIw+3WwSZgDXxxdDTVs0in0lKcCGBoc6dJZNxFKQ1vbgSgPiV7FIjq9FkrEVhkYuGuyfI7ct/tsmDQwEIUnQWeC6maCwqwGI0YCQcLtgGiqdCVm+V5HVyLLFmN+RPprhZ0j5Pt0ntSTY5KQ4/2MCaF/CAg4h1GlgNdDBqN+o/Xog3JI9gJOFHQk3NZcbKmQ8T+JBr0CtPfH4u/gzN3ZJL7KTMZ/QaMDet8MCXZ0b/bheRa9nLA+fGgRbG+Mx/+Yzp89/og8AwyMgxEzqSvmbYxVbcutTMARzLk5GyhVeYTh6W/3uIf7OakWtzkuWIzgS2TE3JOmr4+izMgvfNxQPOsYVX5kiyG2Ozbe1amKt+TkPD0s3qkWSf4scadnxmBmWdfCuCj6IRoNOWvUw02pPGC2cGcRJtSXxOyfpJ+tzwBbu7fRETU3ySS8ksY4PI+v/Qw2w/U6zP0xdEWKVxKgkaa94W/eldyNY3p7vEqgkUIB1pdHaalqEkaCN0q+CPHbdCju65aJRAhEz/GKX2ccbK19xlcbjvJcH8Dk4ug0bpFUAWBnkyUV1z+cJQxNaUYLkyjWgY1vXybpVQQGwIZL7xdFS9iKJKZp5l2WXHnhx3zg1l5dr5GdU1ba+4ocelFA75clBfVBPzIzpC5ova/k/S1I5zqYvdcv5cI7zi2cY1sXbO/4
  template:
    metadata:
      creationTimestamp: null
      name: ha-git-credentials
      namespace: home-assistant
