---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ultrahuman-db-credentials
  namespace: home-assistant
spec:
  encryptedData:
    db_url: AgCZLN06PvgjLtY/oelpqy6JoBPTNsiTKDTBQypgp2efoJcFIqhDWN7ppX1X1eFpVpA5HQ95kqv45Vv5QchNM9dkFXS8dFO5DW5O0brhApPjeg4wXrPHhQ77QJyL8utJq9SfUPKgqGCUvbkhV+4SUsucfpTcda94cKrsZnUu/ZrLlXCbCuu1P72K7mGVVI9125Q3ZJySW8GRkm4Up9wmXhVUsU8PkvI6YEeyudwYC16gZOso5Qi1KLVlbHr473EDxMGN64oNPuU4pv1OlNeXh2VAbPM0tb0NSJfclkr7E7zcA3mfem5DZKKrYCzWi26HpSYtH53Q38zORY+0Y8gdUf3OfmxYUaFFHJ88DLlI+zudkHFe3STVAhApAPfE4NJ7duX3PkYR60jZlkPiMrNuALJYzGfNiov9lEgy9F3I2WdOJFTEf+pG3L5haaqJFwkeNpR9ZtGs00RMiEt+oawbsHVNXRElC85KUOEfFTstHl48VhrYNDWtCCikrnWbytkwAj+0jYA+DWSn5mMiOoCwDQFVD72OvgDp2YQKJAf2Iza3zkr670DbhEYW6CkpSYfN+MctN7PXoZLD4LywCRJJjEBo/lVwmU9lTknGHEx8uLeHqNtBiM1mUZ3aEAL6ixeyrNQr5LthsZIu8XU3uu65XPyUYuWfl8MWLvT5L4rKxAolevGgyzwMMHhxogU7xXuDj1/LHT9CJEQspiEYchkPeKfqY6rSwDN4xhY/Uoy+nkKJEw5F0lI3AeRTW3AZOzOk2EXyQJwLUzbEgAKd4wKvNEhTI8I0nl1rf8JvQ+6t5yNM0vF8GJ4mWb9FytB5Cxbzst+VBJJebBwMIxLtUJWytuhbbL9UIC9U7g4C6jRsFqtlcNt05A==
  template:
    metadata:
      creationTimestamp: null
      name: ultrahuman-db-credentials
      namespace: home-assistant
