apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: foundryvtt-tls
  namespace: foundryvtt
spec:
  secretName: foundryvtt-tls
  issuerRef:
    name: {{ .Values.ingress.clusterIssuer }}
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.ingress.host }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: foundryvtt
  namespace: foundryvtt
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.host }}`)
      services:
        - name: foundryvtt
          port: 30000
  tls:
    secretName: foundryvtt-tls
