image:
  repository: ghcr.io/felddy/foundryvtt
  tag: "14"
  pullPolicy: IfNotPresent

# Name of the SealedSecret that contains FOUNDRY_USERNAME, FOUNDRY_PASSWORD, FOUNDRY_LICENSE_KEY
credentialsSecret: foundryvtt-credentials

persistence:
  size: 10Gi
  storageClass: ""

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: "2"
    memory: 2Gi

ingress:
  host: foundry.eldamar.dev
  clusterIssuer: letsencrypt-production
