---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: esphome-git-credentials
  namespace: esphome
spec:
  encryptedData:
    token: AgAO3010p2cerGjCC3d2xR5uZF2/9zXE++764wNWaGg0oo81wT3SR4Lg6HIVb/Hk4ldi+we0H3nIpMZ/YlpPZoxhilyZ2vu2V0AhqEtLhCbMHTTXOngS2st3EzlHsdYu/NJ6y9BZoTBr5n7xK5ZP9w3hPaJrcF9M+x6GIh4GXv5bXbSVxraUITbIQgzAS6Gv8VITp1zlZ/amVx2gjLsnNMDXRhaVkPeIaMwLnZOLpjvf45jbaeFt+FmFRW9odUMU6hvW9hGpPcKSB1zSEohuWsjt+poP1QtgXLah/Wy2wyfgt7SoJ7iKeEVzzwhX8Sy1GvyqQnCyQGMd2IjCj7vKv3rKq2ZrehsCQVDsvG/C7hddGnIO2otT65yL4ty3CWXH0VdcYEpRFcc1eRnvX2j7Upx6grl7n6fJA5wLGyoW1L/v29g5MNCEbFZkbM68np4Pg5AhquKx8wWVSnDMHL9NN59y2d1CVNlbjuwTFxk/fLRcOYm0+rKDwF3LkoCb8XMDoxAOW5p4efimamH5S0t8LFLzus6QT1N5dS/d2plImIPB8JIjLRhdObkXhZpEoLD/l7HfeR9lPovpDIKANjfoNEw3+AfxyXGLbwQLILuuGg1gaRcCGy0USgufdWP9tODyl57f2iiStSVLWsJPiMLAdaWj/4Zn1oxkEMc81Rawk9rL5C7C4Fb7NaQaxsdsmJlOVuld6/sz3O5dDWJJoh6xzPjWuJDiz+lfRvFt9WKBy/D/FlDE7sSD/F+N
    username: AgAb6eSqL1o1RNlW/G4xliGgx0IP4hHoCHzIvevzjMCdrLC/53bUHC8ILsaUrweKD9bamU8JIGA1UEMW1u6PLbH4uof8e9Snz4EP/WBKENPXoLcL/7asHnKjwmYOPawi8GFyF0afsXdK/6l4I1x7n3bgXt3smtJ5ZqxVuat9ews4r+ZwpF9eyStt9ZMRSdCT1M2FHFk5RamKzpRF3MJnwbeBgnBFjMdmZZJtmSOJQHnjE6hjH1zi7hnWrpHK23C0Sq3mrawWj+gQXnb+5rf8HnTRSRoiYGxZcDKP24StPDuW1nAsL5RJyY0yG7DBFTMRJcbdgYk+4XOXB6G+XxiHSREIFPy9tG1zWxhtSDUG6T57imr3+CPzNVk2GlMj+wYM7wmma8kZ2d6JP0uhUBAl8QBfM+babyM+sHhMay7KUlSSojukd6Vh9oBmtUsKiRSnnDmSWyMtgSf1C4OmAfK2czfqnwD40BaRyPEgubEpvd1FDviTAEtf0Cyz4VdiPfmDjIFy8H0kWCnrp4dXqehP6KEOAG5ZCViqyB0oA/rSp+DQEFBfX8EFCufzuDJLfWXQOQcDo5XNpOYgyYzdanTsi/OR16lKuHETom1dvTSyvtRgjCblWEM3/c2Mib5+QcKvupkmSm8AT+s+M1CST908tjnlxiLYseFGIscxrbnASeg7GONKm1Mjasu6Ak0N1ZNmJ5VM8QNUpasP
  template:
    metadata:
      creationTimestamp: null
      name: esphome-git-credentials
      namespace: esphome
