apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo-runner
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-runner
  template:
    metadata:
      labels:
        app: forgejo-runner
    spec:
      containers:
      - name: runner
        image: forgejo/forgejo-runner:latest
        env:
        - name: FORGEJO_URL
          value: "http://forgejo.default.svc.cluster.local:3000"
        - name: FORGEJO_TOKEN
          valueFrom:
            secretKeyRef:
              name: forgejo-token
              key: token
