---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: game-engine-wiki-git-credentials
  namespace: game-engine-wiki-mcp
spec:
  encryptedData:
    token: AgDHrk/UsPV1z+qNj4DYpe7qD28B++Q9gY0UknPwVq8Ts5j9c30h5vHAy/pm+wqMLnoTHoS+SnLev1ytTX/3dnLRKAz3tI/eAGV+s480yIjOAmCozhswP8FZG/UQqRZA/nmcrqOnosug2HAbzYsz0o7EWwafTDoYD7vWJKQIv+jcdqrRqP8lSy82rJLNWyj2wc/lHXQrVl0d8m0Co/827glxL8LLrqEUw60Kg0MsqcTvSQvVOCnhkvPZxOml+3yl/WtzaJZZWdkkiv/O7BKvc4KF4WEuSlnxxMGE7dK7hB2cSWdcMJEXsTF/BqkgsXBUKVRD4AORoqICRmlGVIVhcZWJtsCsUyAsoX3iv60A9thLnWKbbKes8pSicSgsl6JxYYl1dLxpnCk4gOMZuQo6vy9pVmg0eCTiW3Z4OoVq6sY5zOwAT2X1zBwmRs96mAT1fDe5tpGWoGe7EUMSiGNqUw+pEk8kdgZnl6aKeD/rEXr04MOZ7lyfHWuXaoxKHq8skIXgCsTHCmULwHOYsi2CF59lwvoPgygvhDw5Gca8crxJc2CG1ATpeARqgaAcDxAlp0JP53xgNRmFD/SdMKjlzJaRo1Feuqxmdhwdd1tdmfskVbZzYggYQD8xfoReu8TPOPK0rSzrHSFqyh4QsI92HnpaTrMv8H/o7yNhSqvrUa2AQBiyDM1MwB1bM6W6dcTWv3h2HSp5W4kKizJjMnObcS796ZUdgWgVcLTNNmSohZ9wAkCQnMHln9vZ
    username: AgAuRS9gBTXfNDrEJrnt6XQ2HWBvm6eB8wh0rnQyWWMnYRc4MuIHDVpNYD8aTSYAyceVDnAoXQwuh/03K4YxVOHvBvXvNUQSpztuuvSzcJq1Nsda7gYENOy97LR+H+FFmY1bLNHpVpS5XUZAXptzxnFaXzkjKA0A4Vmq7yVjrZS/wo64Ofn4qZHqRh8+BX7j9fpyC7M/s8Z25lY7AOdIxr4cYD7+TKiZWiqSSdmxHolXkssQP7ASvmcQvPOjuEKFPlK/5wNnEhtdBEdttBkDbfGoB74U1fDZa1Cl8bg34MdWwZRLF09GaaobSEpNSb487nTLjmPkEXnaBs38cAnqAO7C5Z88t4BUatwAs309xFbiEpCHJ1lvHTuLmExahiSL0PJWFNBvk6jmAeTM8T14MWbY8BkuBnfxihk/FjuVZBXCcsy3liEnXrgvJ0AECc7Zotr1W4dWyiE2TdCUPWylac9+qXsKyHbVPrXJ5fGG99VAHGYPLxut8CdnsYTc0ykYJpw1ZuJ+HR8SRKFWQMdIkxbiqheKkYiwDu3EQlwerTIaRym6/DCrfovd1LLxHCCnsq3FR95wWrRR6DHorA/PM58g/+BhoUKwwF1Zz/0NiLoHH796nli4bU20poW4q+UBrKDgvXBOSCQkCy2ApAmTZhtS/4Uhq3iOkY9ldyi5ZTIObbPOAflamzPHI4KvXIGlQ1IroS585Wa7
  template:
    metadata:
      creationTimestamp: null
      name: game-engine-wiki-git-credentials
      namespace: game-engine-wiki-mcp
