apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pixelinator/Feanor.git
    targetRevision: HEAD
    path: gitops/apps/glance
  destination:
    server: https://kubernetes.default.svc
    namespace: glance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
