apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  # Der Name Ihrer ArgoCD-Anwendung
  name: glance-dashboard
  # Im ArgoCD Namespace
  namespace: argocd
spec:
  # Ziel-Cluster (in der Regel der Cluster, auf dem ArgoCD läuft)
  destination:
    server: https://kubernetes.default.svc
    namespace: glance # Ziel-Namespace für das Deployment von Glance

  # Quelle des Helm Charts
  source:
    # 💡 Das alpineworks Helm-Repository
    repoURL: https://michaelpeterswa.github.io/alpineworks/
    # Name des Charts im Repository
    chart: glance
    # Die gewünschte Chart-Version (ersetzen Sie dies bei Bedarf)
    targetRevision: 0.1.1

    # 🛠️ Wichtige Konfigurationen für das Chart
    helm:
      values: |
        # Konfigurieren Sie hier Ihre Werte für das glance Chart.
        # Da das Chart keine offiziellen Standardwerte hat, müssen Sie 
        # möglicherweise die grundlegendsten Werte (wie unten gezeigt) setzen 
        # oder die values.yaml aus dem Repository überprüfen.

        # Beispiel-Werte:
        image:
          repository: glanceapp/glance
          tag: latest

        # Konfigurieren Sie den Service-Typ, z.B. ClusterIP oder LoadBalancer/NodePort
        service:
          type: ClusterIP
          port: 80 # ArgoCD wird den Service auf Port 80 im Cluster erstellen
          targetPort: 8080 # Der Port, auf dem Glance im Container lauscht
          
        # Konfigurieren Sie die Persistenz (sehr wichtig für die Konfigurationsdatei!)
        persistence:
          enabled: true
          # Hier den Namen des Persistent Volume Claim (PVC) setzen, falls vorhanden
          # existingClaim: "glance-pvc" 
          size: 1Gi
          # storageClassName: standard # Anpassen an Ihren Storage Class
          
        # Die Konfigurationsdatei für Glance (glance.yml) muss per ConfigMap oder Secret
        # in den Container gemountet werden. Dies muss manuell nach den Vorgaben 
        # des verwendeten Glance Helm Charts erfolgen.

  # Allgemeine ArgoCD-Einstellungen
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # Erstellt den Namespace, falls er noch nicht existiert
      - CreateNamespace=true
