apiVersion: apps/v1
kind: Deployment
metadata:
  name: ceph
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ceph
  template:
    metadata:
      labels:
        app: ceph
    spec:
      containers:
      - name: ceph-mon
        image: ceph/ceph:latest
        env:
        - name: MON_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CEPH_PUBLIC_NETWORK
          value: "10.0.0.0/24"
        ports:
        - containerPort: 6789
      - name: ceph-osd
        image: ceph/ceph:latest
        volumeMounts:
        - mountPath: /var/lib/ceph/osd
          name: ceph-data
      volumes:
      - name: ceph-data
        emptyDir: {}
