apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgARYSFnUqpHqYGvcJ9lf+jqVUAvGoD/0jqHgCB5ceukFDZIThg/3ncJtIbUBJrtdo5kvjVTEIzjQrIGBUwAFqKTp6kgRW1lQAXlF9aYe/vm/IJn0dV0KltMNFcgAG06YiHNCu/XlR7EaKOZ14HF+vt5EXuUB38veZ9kRihvlzn0cA6DkIc6II++JJ2ydWow3Xq57ocCwIrTzbrMcLD/5xjLSiLeGVb0lNzRro65mNlvkxYSULcbYX5pmUyztgfEuzEUyafH9iqdGfh/qi4QODySvtHX8HJ7QwXn8QS52GVyJzVqoYiPw+lPQxXOaWjL7miXkC4sIXimbhRJzQqO1tLterOjW6/GdupURV9lY4OzXBjIHKzo9jb2LorNJ08QzRUswE7R2ZwZ3Hmrfp7djM1fpS5/t66ekUDFPXCtcpfiaK5qNCSfZS5HQY8UtjjKDewxPVHWo55gDcIL3zGJgVAEVN4NsefooVjTJOyWxgJw1eCl/OZLDSGqnavGpaKw1kd0+pZ+pVl6FmH7Lm7lp1L6NgnJtAs/pepIwHv2hKXnegrajVgjfEVUS3JiUzWhZY+8auLdY1rBDLLcj8t+hECVzb1NXP/BtnEYoy/D5cVXdgYnb+ENFgktpxpjdWiOo/V0VjdZPyJzVufZy+MUlJ9w92vbkSEXdMkqK7nsNQVeh3hqXzdIa5iiQOBXi04+3dmAzSvezT4r0f4AsxzVuwzGwQwdbBQtKT0b+INqPr6G9pbEfT+UcmXG
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-secret
      namespace: cert-manager
