---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ultrahuman-api-token
  namespace: ultrahuman
spec:
  encryptedData:
    token: AgAYs4si5M0nJwk2umTXu1dnABYJv8CQnLnAL4+moX6M6jppzByqNHLP7uyUwEAvt38uYnWvdT5kFT7VRsxLlrb12dPaw+aDME8GQbrcXb789XaavYcVReuVt9fnnfEk9LU20RRQ+i2jiek9XnbX1/Ixhwfadu+L1xvd8M0OpqtNeL53ca7xhDUH2k/yf0uKElANjNi/z4QL+dp2KDc2euARhMdro9BT5QbXzmyjZMBq+Z/G66ieVqwSNRIcV82baEPB4M4qfE2zxjizkSs3mdORog4v6xaOQkXV/lVWZOmfu5PIBZA4kxnVw98eNPfOaeSiruXxNG9KjKi5brRbEPaYEUu8gIdrgqLhq5uGV9TzJ017TPbJafOvMfadGMId2x7wrPxPjcJEeJIL8JzCgr3XppU70DR8TIU+mfKj6yUi7FtfW30GVppCMQOrAGicdB2xFwfWtEmyLpHvbPRF0lAv6WU7jZTh96uJVoftn8CyNqPi7gphD4eLNzY3slxJ/eU8fs87Y20LxqwPZUSDn3A3K9oQ3jV2tAGVaka3Q385HO8E6IdQOuwyWau7YgrrpRL1dQ8OxNXOLJwZg27Wv4/Voj+yICdbKGUk45sdib1IX0epN1mbkDoD+T8smcW33URMrXIkEGtY453hVp3BWUJmMBXX5tRMP5J5eTxF3P0EeIVZUkQOXFVTi8V63E924O+Yd3yYlgc+4cGO8Mz51OFKx3CJtPLbX4YSb2l4CfRRC/YFuoF15KIxa5ElMScJWmvRzqNiLgli7k34GOAN9BlKwWrRn42/0aREg7QyodmiKn2Y3tcpaAEw3h3fbleRMQBwAg27JCV7jspyZUtzolP9a3IMmEibZUnd9Al+WOmqxKXsf02dgI9YVAsXKOFFwC3CqVSzAWlIAuYnSxIuHPtd+tyniVpnIIPoW+8rhmI3TLdIvxv5NCedRZip9EyObhU=
  template:
    metadata:
      creationTimestamp: null
      name: ultrahuman-api-token
      namespace: ultrahuman
