---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ultrahuman-registry
  namespace: ultrahuman
spec:
  encryptedData:
    .dockerconfigjson: AgC8rVV4IxT4+ehl7AZJl97egq5bOABtI3v2Mqk0IoxkoMGCY1wcTK4ma5DYKNQlTiB5aSVUqYcpyzxKMosa5LgsTEAfuf1k57y1ZjghE37JnZPnj3cIam+3tNtp+zDXQ45bxKh3rij1b7+3lFs7CO/atBEeUFgeH8DtZMGwMi5zeUxnVUU1yce16CXdQ71IOxZN4Ni6kVB/G834CcwZE5tBab0Q8rQHtNpH13O2n9wPHXK2kPBl/EiUiCbw9DFID9rTpSE0U2IasCScE4Ps2GONk6k5H2fz8bv7aCMoqXE6KErp2hX5+LybNED7D4bZEr4KXd0qEubNr6WHoKzwBx7akqnbvUUtwRVireHbRkB93zr8B1kRfKPp4FYTxYHtoL0gBtxPX8jTP685GDSr3TStRqNXbGL4tBw0By1WqkVCQ3t6j6GGeYzzKiGreJK9DzDZ2mRRV6IPVMs+ikP6pI236su0/8IO0ffC8l4p2pT/dI1ClCeY+hIlw6rJNlvnb6qxxUOhwbBBpt3GeSxYODbc2W5vjP+TpNOF1okdz4q5qJG7p+4JGkBuRQ8CzbYgyDnpOrhAjkjY9PskoYEjPExqWx7+Cf7pkAXmeyZq2tO9rHxTjDPDuh4qIDlknGS233EuxTjBAxicl8exrU2sDo7d2PWuOeAT0nTul0T6iCRe2iLoVm88ZTeQP7aLj7MKjXNAAnGfpj/Ii7aoy7FOmyPEbivYzRfJR09rsMnsrTrgQjM0zbJpfZts33yyLADIOFBzMuO1FDpTAUnG6NK3NnhSb3qyLddsW22X51QiavVmFexslDlVc2j5bFsyGJJi8a02VDHSZDTfH9D7LwvHeOZIhpcDHilKJzHLp+MT2m1rBm72J6sGJpPyBlOGsQDVpzl1bz/S6YoPnFA7zqcXhZSOdu3jIS2HvUHOvFLaH7QH78dcFXcaiVSTuiSlxgKCgek=
  template:
    metadata:
      creationTimestamp: null
      name: ultrahuman-registry
      namespace: ultrahuman
    type: kubernetes.io/dockerconfigjson
