---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ultrahuman-ha-config-git
  namespace: ultrahuman
spec:
  encryptedData:
    token: AgDNqXr5WGWHKbJOvQjcucakVphI5bLg2Xwp47fvn1pw8rca2mg//AXrrUnqtX3R146LkO/YqfT2ICB4DcDjwPj4PyyB8/UMcFFzMUD0DSLWdJXBoRyLWr3l98DiSfacZzBwXYsi+tyhQ9+0WQifXiUoWjzg08r8luSiJEsjTDVivFTTJWqWTFEamfSEHtdiPWRUX5qieLMjK0PpkeuPrwMcHKeTRbD51MET0CuKUaju9aAdfi3xd96qQ5D/5L9krJGIqVVnvXckLi6G1x6TLSbWmwfBTNWeG5K7pxfuw3qwt9y0J9z1dRc+IH/9xfITlhLP/tDy44nS9ExHN9IqiQ98hB2WCiO+UVzgthvpgeUBnThbyVLfsbQHnczVNG6ugky7PpIJGEont6O/S3TftTtSKSFSscm4HYUUL3LcJEkT1ke2Dcl3/Lt1+AemN+fRPtd8+zbxxpydYOXYmcymeKjlWUowzXA1Duj1g4/8wv4CYLJmv8vmgOaolDW92f6Cfyqc5Q/AjJWF/D6ETi9TNc47BDx2j+ngmKgOCym6yjXbw70f+7/K77r4NhJwn0jLrYXyIpuHkp6DskPdxIGKNkXWuam6N2TNYkyQV6ltTzIgGTRzc2In1JZKvJ0v9KJvjKEg/fwwW5jQ2CFTgB5Hgk2a/QQ+u8yluo/dofSGjqnIRotLf1lt/KEW5Uz9umxGY4ILJjqLmr2Y1DICGwXTqfvPy/T010No2Sp4mnUiVKiM9UabiS4rzu+x
    username: AgC/oP59oarkGotSNy81g3iTRXYL5pK2ADdqdPQ2Xq2dvgIHO+ZLXF8Jyvs2F1u+KzNwiWF8uL+W/owJ+N6rfGcjOsvSHqUuxJ2uh3HHawBa/BBNtG4Zje+nkcCTEH67dFC5yrg9R7x768HNlRSR77ctEA2Eh3b6sqYPcGPynFt72eGC0BcuqyC+mzM9bUr0/w0JM/SyD37XmLPuj78gQ3y1k3t0WaGhAk3DQhvRH51TGo9B/N1Giymoncqe3dc6B4L5FKwfcRcK3iYHaExlItQZLX0Rob772qYbpCS8ZWs6ARp7sNG3Tq7paeR+NPkOATyUxKuOnlbymD2ccrk6f3pv7CkKgI0NUZLeROw4tHTvkw7mru9U4XIDjJR3FfEeTfB0TJ949nzkgN4bbbm85RuEaZAOUFKNHupYRj+HJfr08asP3WPe3WuNcjr9B04gyIn8mEJfgpAAcdwyyKGeFWP8eqN2XqcVyw+es0S893BOJctAGo21vgq+lT6VWTqzFulj1VqTGWaqLSUArVHT0y4Sq6BVohSzFlSi1a5xDOy3on1HsUljDPMH2v7mLyD01l6AuStjzmwq4uGXozSpOKUab37sZTJ+jLDFZi4e8hVEYialnyUzJtQuvttiGsutq1ChA1QLLth/gc4qBL5CjQLPpe3W4cGeYphZvrNsdCS6IxqzRbUtHGLpyaWnGqzvXPtHsTkJ6BZb
  template:
    metadata:
      creationTimestamp: null
      name: ultrahuman-ha-config-git
      namespace: ultrahuman
