apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # This name MUST match the 'existingClaim' in your values.yaml
  name: dominic-movies-pvc
  # IMPORTANT: Replace this with the namespace where you deploy Jellyfin
  # If you don't specify one, it will default to 'default'
  # namespace: jellyfin
spec:
  accessModes:
    # This must match the accessModes defined in your PV (01-media-pv.yaml)
    - ReadOnlyMany
  resources:
    requests:
      # This MUST match the capacity defined in your PV (01-media-pv.yaml)
      storage: 10Ti
  # This MUST match the storageClassName defined in your PV
  storageClassName: manual
