apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: forgejo-oauth2-client-secret
  namespace: authentik
spec:
  encryptedData:
    client-secret: AgBYvTBRdVC0/28uhwWAFSM58XUkG6iRDATcUESigS81F9lM/bv5/MmVSG3Dg2OzZBM/zUU461LymMk1oBpagBXjGxfAmv0EkWCcAKfpnTOTG3RPqy9IeksxyFCEC47aBWUHxPxi3n56FfoQT8Fa4t6c9cfoj9VOzevbp1u7Hap4ENHeJg3irFcav0SMPdG77wbliUj1351NE+bK1k0bizKSdnXvevsI05EK412W5OvblwNOyIne2b0qx4XenT2TWGjCBExswXBSHR2BJ0qUFEeeCgbg4j9T4G73mNJdY5Qc/m+uash6RRsJAZbcHW51Gdp43we9WAiDHruhElYdkFhRxja32HujCl+D7gX32Gydxq3IBvZi5hLoqG0ozrBMCnvzkDp45Ppes5wMRLY9RMZtX2YrSgPOCRzmrSGkOKUaMaWd2HjKPnJPe2SKaYDukYW9Exyw3liBv3wCiivKZmoyNVe2k+o3kAQ53K0wYvlgNHu6UlszTFeIpR8OWbpSJfdCyx/i4ZvxujqC6aEB+6erjb+CKd+c5CHRRevhe/884LLgVlk9sFvr4C+gzlB2c+tc6VQOfoz42zgmG2DPq+a4cZvH5f0QbS90OAl9th95YazbFEdPqUb3ZQwv/vied5yLpsGy1b+N2bC+Kisvcx1CzoCQP8Lh5vgBycyZm/xm5T15HDWthsOacpRXJ/fVzhS1wEXOmdXSJUuEOkICOumhWLmpvnaO8WikKY4q9aqzqYJOgFcf1F//0+iNnP4bMGG479MPdj80hzi+QhO/wqTkGXxvbU94Awu5aawuvgme24ApfaeyNhqmzeyWfyzXpKjMJKRkuX4UsR1+fUQBcZbePh23XDtRqT1edJm+
  template:
    metadata:
      creationTimestamp: null
      name: forgejo-oauth2-client-secret
      namespace: authentik
