apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: opencloud-oauth2-client-secret
  namespace: authentik
spec:
  encryptedData:
    client-secret: AgBlvpaDyy9AclqvAsPzmQnelX6XIF9OfOdXmg8R8fqYgUo5fhxGH8kJivSpn/JH1H8ODxfmJOEILEO5dEEsS/UNAEYks7BbWc0HrgklBzFLrgrRlxpHKGY8oq8RN3bgzmgFHTdMJEWMEiwqmF3EBt/yLTVncH2Boh82GNJAhcJptmx7lD+BdgeXrXVZ5GvxX8nGBl7yRG9EZ3IjUKTEELfCSuH1HOBDVSydLQbRR9DOoKMHCMciHuqMJWvzuuSb9XUWcTkpyMh7bumOxY7U+3BLF84+xaj1ozwh0jtnC14M5s7BdjyDTR9GTRAzvfyV9XeY75uDLrSGbDQHVw4H4QBDhxQltE1GjaOafszN6nV4+ICYU88thizzTJutkRFkjPW9vdq33fQHtVoifJmGWWO+dHB6Spx/kw+93Z2zwOYbQP8D+8nisHoirjx2Q2/OlqPAP60YIKeC5l56vTPslEJHy6RHUy+t9bcVArAf5E04e3a6GPnnD/88FiXWCwR1PWNymHGdbBcQkioBy8RCLts0nsaJaGvB8zpV9vQ31HD7vdget9JfITOFRl+JKyVP2kBoSYMr11eYSZCPU90VhQ4lNH3qZy2HLNRZrN7S+GBpV6qG6kqDdPn7CANHAkBYYobQsJSjAJyfeD/hC2rFZeuiMAtYlOwuZReDSb8v05AV5IbscqUpfOD7s8UIcbZqxrC+1JPwLiBGA4c6C6nZBxMIJ391F4E/ielOHVSi2MelZMoqWJ9An3T1Z2p0cGLHj5tvebHAIDJfybWtW6U0Tnx20nVHmdo/cBuGfI0U0CfKWWdYUXat8obNBkqSq2CzwojKCC51WUSGgkCPKE/+/7SfhlZ0E31/a2dafuc=
  template:
    metadata:
      creationTimestamp: null
      name: opencloud-oauth2-client-secret
      namespace: authentik
